### ISSUE TITLE
Full process

### ISSUE THREAD

**Issue by javico-dev11** [The-One-Reborn-developer/Telegram-BLS-bot-Russia#3]
Hello, how are you? Do you plan to go through the whole process of making appointments for a Spanish visa? What you are doing is very interesting. Will it work for other countries or only for making an appointment from Russia?

**Comment by The-One-Reborn-developer** [comment]
I am planning to do the whole thing. As of now I am only making it based off this visa center`s website for Russia. But I know that the Belorussian website is the same. So maybe it could work with others too after I'm done.

**Comment by javico-dev11** [comment]
Ok, thanks for your answer, I would like to try it later if it works in other countries, please do not hesitate to contact me when you finish the process, there are good opportunities with a bot similar to the one you are developing. I leave you my email: jcordova849@gmail.com

**Comment by The-One-Reborn-developer** [comment]
> Ok, thanks for your answer, I would like to try it later if it works in other countries, please do not hesitate to contact me when you finish the process, there are good opportunities with a bot similar to the one you are developing. I leave you my email: [jcordova849@gmail.com](mailto:jcordova849@gmail.com)

Can you write me in Telegram? I have a link in my profile.
